name: Destroy ABC Startup Infrastructure

on:
  workflow_dispatch:   # Manual trigger

permissions:
  id-token: write      # Required for OIDC
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::165742852730:role/GitHubActions-IaC-Deployer
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Destroy
        run: |
          terraform init
          terraform destroy -auto-approve
